[package]
name = "connection-status"
version = "0.1.0"
authors = ["superlou <lousimons@gmail.com>"]
edition = "2018"

[dependencies]
gethostname = "0.2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
